name: CI

on: [push, pull_request]

jobs:
  nix-build:
    name: Build with Nix
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Install Nix
      uses: cachix/install-nix-action@07da2520eebede906fbeefa9dd0a2b635323909d  # v12

    - name: Build plugin
      run: nix-shell --run make
